### ISSUE TITLE
README file - badge not rendering

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/software-peer-review#143]
Looks like there is a bad badge link there..
<img width="709" alt="Screen Shot 2022-11-03 at 5 46 16 PM" src="https://user-images.githubusercontent.com/7649194/199840648-d441ca2b-9f45-47f7-aaa7-c6c41bac8fe9.png">

**Comment by sumit-158** [comment]
@lwasser the "CircleCI book Preview" is not rendering because the image link throwing "project not found error".
here: https://circleci.com/gh/pyOpenSci/peer-review-guide.svg?style=svg also, https://circleci.com/gh/pyOpenSci/peer-review-guide

**Comment by lwasser** [comment]
hi @sumit-158 !! thanks so much!!! 
i bet that is because we renamed the repo and just need to update the urls on the badge to the new url?

https://app.circleci.com/pipelines/github/pyOpenSci/software-peer-review 

any interest in a quick pr to fix? (Assuming that is the issue!?)

**Comment by sumit-158** [comment]
Sure I will raise Pr soon!
