### ISSUE TITLE
Suggest that reviewers create issues instead of adding all text in the review?

### ISSUE THREAD

**Issue by choldgraf** [pyOpenSci/software-peer-review#17]
One issue that we ran into in our first review is that the review issue can get *reeeally* long if there are many comments etc. It'll get even longer if discussion etc happens after the review.

The JOSS community recommends that reviewers open up issues in the author repository, instead of discussing in the review issue, and instead just link out to those opened issues. E.g., here's the Whedon "new review" comment on a recent review: https://github.com/openjournals/joss-reviews/issues/1408#issue-436431334 (see the wording just under "Reviewers and authors:")

They also suggest this here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

Shall we adopt a similar suggested workflow? Would love to hear people's thoughts!

**Comment by noamross** [comment]
(Hello, fan, lurker, and RO editor here 👋)

At rOpenSci we keep reviews in a single thread because it makes the review a single readable resource for future users, especially editors/reviewers at other journals that the package may be passed on to.  It can definitely get ungainly this way.  Sometimes people put their reviews in summary in the main thread and then open individual issues, linking to them. Authors then respond with a general summary of changes, linking to relevant issues, commits, or PRs in the package repo. I prefer having it all in one place, but there are definitely trade-offs.

**Comment by kysolvik** [comment]
Thanks @choldgraf and welcome @noamross!! There do seem to be tradeoffs. It's nice having all of the review process for a package in a single issue. I do like the JOSS process in that some record of the review changes are then directly visible in the package's repo, plus it keeps the review issue shorter. That set up might be easier to do once we get whedon or a similar bot running to help with linking between different issues relating to the review.

Maybe we could discuss during our call next week? @lwasser, what do you think?

**Comment by lwasser** [comment]
hi @noamross 👋👋👋 welcome to pyopensci!! we love fans and especially ones with all of the experience and expertise that you bring to the table!!

1. we are happy to add you to our org if you'd like
2. please feel free to jump into our every 3 week meetings at ANY TIME if you have time. i know you are busy but i'm happy to add you to the invites even if you are too busy to attend
3. your thoughts are great. 
I love the idea of a mix of @choldgraf and ropensci and JOSS. what if
1. the issues to address were in the review but
2. the issues IF created in the other repo (i'd prefer this for earthpy at a  minimum as we have a change log to track changes against issues and releases).  are then LINKED in the review as you mention some do.

this might be the best of both worlds. REgardless let's plan to discuss at our nexf meeting as @kysolvik mentioned which is next THURSDAY at 11am MDT. happy to have you join us noam if or whenever you'd like. or if you'd like to continue to just watch please do that as well!! i get time constraints.

Happy weekend all!!

**Comment by choldgraf** [comment]
I'm +1 on linking the issues that are opened back to the original review - that's what JOSS suggests, I believe

**Comment by noamross** [comment]
Thanks for the warm welcome @lwasser!  For now I will stick to watching the repo to avoid taking on too much, but feel free to ping me or the other RO folk if there's anything we can be helpful with.

**Comment by lwasser** [comment]
hey guys - i did a bad thing. last week in a rush after our meeting i committed directly to master BUT...

@choldgraf we talked about this in our meeting and discussed an OPTION in the template where someone submitting a package could check a box that would allow a reviewer to submit issues. With the expectation that they would LINK To those issues in their review. my commit is here:

https://github.com/pyOpenSci/software-review/commit/236b482fbad4b0b3b9b8bdd37d992e656d9583e0 

Everyone liked this idea a lot! And it does follow with what JOSS does. We are trying it with our current review. SO it seems like the task at hand is for someone to update the dev_guide to describe
1. what it means when that box is checked AND
2. how a reviewer should handle submitting issues and CLEARLY linking them back to the review. 

does that sound reasonable? i have tagged this item with a "help wanted" label in hopes that someone might be able to help us implement this. And perhaps somewhere we can keep a list of things that are low hanging fruit tasks (like this one) that people can help us do!!

**Comment by lwasser** [comment]
ok this is also a very old issue! we have addressed it however. we do allow submittors to check a box about opening issues and pull requests. and this has worked quite well! they then reference the original review issue. i'm going to close this now as completed!!
