### ISSUE TITLE
✨  Turn software-submission issue template into github FORM for in software-submission repo [GITHUB]

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/software-peer-review#206]
When people submit a package for review they do so by opening an issue in our software-review github repo. [The template for this submission is here. ](https://github.com/pyOpenSci/software-submission/blob/main/.github/ISSUE_TEMPLATE/submit-software-for-review.md)

It would be easier for folks to submit using a form rather than an issue

[more on forms here.](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) 

as such we would like to take the existing template and turn it into a form using the GitHub form syntax.

Skills required:

* markdown and GitHub
* Git to push changes / create a pull request

**Comment by NickleDave** [comment]
@lwasser just tagging myself in as working on this

**Comment by NickleDave** [comment]
@mccrayjr added an initial version of the template (not me!) -- we needed to merge it to be able to preview. Fleshing it out now.

**Comment by lwasser** [comment]
i am going to close this issue. not because we don't want a form but because we may not want a github form - especially given the new html comments that we will implement with the bot.
