### ISSUE TITLE
Add relevant links in the "this guide" section

### ISSUE THREAD

**Issue by ForgottenProgramme** [pyOpenSci/software-peer-review#209]
[This](https://www.pyopensci.org/software-peer-review/index.html#this-guide) section on the `Peer Review Guide` page is missing links to relevant information/pages. 

@chiinita and I have the following suggestions:
     
| Section on the `Peer Review Guide` page | Page we think it could be linked to|
|--------|-----|
| [About Peer Review](https://www.pyopensci.org/software-peer-review/index.html#about-peer-review) | [About the pyOpenSci software peer review process](https://www.pyopensci.org/software-peer-review/about/intro.html#about-the-pyopensci-software-peer-review-process) |
| [Our Partners](https://www.pyopensci.org/software-peer-review/index.html#our-partners)| [pyOpenSci Software Peer Review Partnerships](https://www.pyopensci.org/software-peer-review/partners/scientific-communities.html#pyopensci-software-peer-review-partnerships) |
| [Review Guides](https://www.pyopensci.org/software-peer-review/index.html#review-guides)| [Guide for Reviewers](https://www.pyopensci.org/software-peer-review/how-to/reviewer-guide.html#guide-for-reviewers) |

OR
Just remove it!

**Comment by lwasser** [comment]
@chiinita @ForgottenProgramme many thanks for this PR! i'm going to assign it to you!
I think removing that bottom section of the page is a great idea - great catch! please followup with a pull request to make the change! if you'd like to add quick links to the top for the major sections, feel free to do so.
