### ISSUE TITLE
Add a secant about JOSS partnership on the peer review intro guide 

### ISSUE THREAD

**Issue by yang-ruoxi** [pyOpenSci/software-peer-review#231]
Would it make sense to add a section on the [Peer Review Guide intro ](https://www.pyopensci.org/software-peer-review/about/intro.html) page that explains the relationship between JOSS and pyOpenSci?

There is currently a very detailed explanation for this on the "Partners" page, but I thought it might be helpful, on the Peer Review Guide intro section, to link to this page and give a brief description about it. 

Not an issue, just a suggestion as I had this question when newly encountered pyOpenSci and it seems many others do too.

**Comment by lwasser** [comment]
this has been implemented!! thank you again @yang-ruoxi 
[see here in the guide](https://www.pyopensci.org/software-peer-review/about/intro.html#partnership-with-joss) . i suppose someone did it but never closed the issue!! i'm closing it now. ,
