### ISSUE TITLE
Remove mention of making changes to the website in the post-review tasks for the author

### ISSUE THREAD

**Issue by Batalex** [pyOpenSci/software-peer-review#275]
https://www.pyopensci.org/software-peer-review/how-to/author-guide.html#my-package-is-approved-now-what

> We will ask you to add your package to the [pyOpenSci website](https://www.pyopensci.org/our-community/). This will give your package more visibility in the community as a vetted pyOpenSci tool. * We also will ask you (and those who reviewed your package) to add yourself to our list of [pyOpenSci community members](https://www.pyopensci.org/our-community/)!

The process is now automated with a GH action.

I'll submit a PR with a 👍 on this issue.

**Comment by lwasser** [comment]
that would be wonderful - thank you for catching this @Batalex and for being willing to create a pr!
