### ISSUE TITLE
dev_guide isn't a great user friendly name 

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/software-peer-review#28]
Given we are branding pyopensci now and trying to help people understand what we are and what we do... it's time to think carefully about how we organize our content.

dev_guide isn't a very expressive name when you think about SEO (how search engines index our website and make it discoverable for people). 

Let's think about using more meaningful section names to help people navigate our content. the question is what should those be?

Example:

CURRENT URL: https://www.pyopensci.org/dev_guide/intro
SUGGESTION: https://www.pyopensci.org/get-started/about-pyopensci

Just a note that it used to be that dashes-between-words (slugs) were optimal for SEO (better than underscores. So my suggestion is to also implement this with all of our urls on the website.

**Comment by choldgraf** [comment]
Oops, I just realized I duped this one in #53 . What do you think about just calling this "guide" @lwasser ?

**Comment by cmarmo** [comment]
I'm under the impression that this has been solved when #53 was? Thanks!

**Comment by lwasser** [comment]
oh wow - YUP. i've restructured ALL of our guide and this was considered. let's close! thanks again @cmarmo ! look at all of these old issues we're cleaning up!
