### ISSUE TITLE
Astropy and pre-submission inquiry

### ISSUE THREAD

**Issue by pllim** [pyOpenSci/software-peer-review#280]
Hello! This is a follow-up of [APE 22](https://github.com/astropy/astropy-APEs/blob/main/APE22.rst) that was accepted in https://github.com/astropy/astropy-APEs/pull/87 . Recently our Community Manager, Beryl Kanali, has published a [Astropy Community Survey Results](https://astropy-report.orgmycology.com/). In the report, particularly in [6.1.3 Standards for Affiliated Packages](https://astropy-report.orgmycology.com/sections/4_improving_participation#standards-for-affiliated-packages), there is a desire for the following:

*Clearer documentation (including tutorials) about how to convert an existing package to an Astropy Affiliated package (without assuming the person who wants to do this is already an Astropy developer).*

I wonder if the pre-submission inquiry would be a good solution for this. If so, how can the existing pre-submission form be updated to this effect? Hope you can advise. Thanks!

cc @dhomeier @hamogu

Might be related:

* https://github.com/astropy/astropy-project/issues/372

**Comment by lwasser** [comment]
hi there @pllim cc: @hamogu @dhomeier  this is moving i think now. id love a bit more information 

> Clearer documentation (including tutorials) about how to convert an existing package to an Astropy Affiliated package (without assuming the person who wants to do this is already an Astropy developer).

Can you help me understand what you mean by how to convert an existing package to an astropy affiliated package? Does that mean the package has already been astropy affiliated / approved? or can you help me understand what an existing package means?

We can then go from there.

**Comment by pllim** [comment]
> Can you help me understand what you mean by how to convert an existing package to an astropy affiliated package?

Let's say some astronomers wrote a package for their research. Now they think their package is mature and could be generally useful (or they just want something shiny for an upcoming paper, or whatever), and they think their package qualifies as something within the Astropy ecosystem, so they would now want to apply to be an Astropy Affiliated package. I hope this clarifies the issue?

**Comment by lwasser** [comment]
ahhhh it does. absolutely. i think a presubmission is the way to go. we may not have a check box for that template - yet but we can create one. then we'd want one of the astropy editors to make the call on whether it's in scope for astropy. our EiC would make the scope call for pyOpenSci. 

that seems very reasonable and would fit into our existing processes.

cc: @isabelizimm and @NickleDave for input just in case they have any given they've both served in this role now on our end.

**Comment by lwasser** [comment]
we have this now in our [presubmission template for pangeo](https://raw.githubusercontent.com/pyOpenSci/software-submission/main/.github/ISSUE_TEMPLATE/presubmission-inquiry.md). so let's just do the same for astropy pending everyone else's feedback of course.

**Comment by hamogu** [comment]
They sound like a good solution to me. On Feb 27, 2024 5:57 PM, Leah Wasser ***@***.***> wrote:
we have this now in our presubmission template for pangeo. so let's just do the same for astropy pending everyone else's feedback of course.

**Comment by lwasser** [comment]
Perfect. i will work on this and will get back to you when there is astropy support in our presubmission process.  ✨

**Comment by lwasser** [comment]
ok y'all - this has been implemented here via this check box in the pre-submission inquiry. i will close this but please reopen if you have questions / require followup!! 

> - [ ] Astropy:[My package adheres to Astropy community standards](https://www.pyopensci.org/software-peer-review/partners/astropy.html)
