### ISSUE TITLE
Add "how to become reviewer" on top of "Guide for Reviewers" page

### ISSUE THREAD

**Issue by pllim** [pyOpenSci/software-peer-review#282]
I had a hard time finding the Google Form where people can sign up to be reviewers. https://www.pyopensci.org/software-peer-review/how-to/reviewer-guide.html was where I went to first but I could not find it.

Then I fumbled around for another 5 mins and finally found it buried in the middle of https://www.pyopensci.org/about-peer-review/index.html#get-involved-with-peer-review .

**Comment by lwasser** [comment]
ahhh @pllim this is a great suggestion!! it's also a great task for someone in a sprint. i'll go ahead and label this issue as such

**Comment by lwasser** [comment]
@pllim @xuanxu submitted a pr for this!! i'll go ahead and close it but we can reopen if you still find is hard to find the signup!  thank you again Juanjo!

**Comment by pllim** [comment]
Awesome. Thanks!
