### ISSUE TITLE
Is the process for updating tag up-to-date?

### ISSUE THREAD

**Issue by NimaSarajpoor** [pyOpenSci/software-peer-review#297]
According to [this document](https://www.pyopensci.org/software-peer-review/how-to/editors-guide.html#respond-to-the-submitter-in-the-github-issue), the editor seems to be responsible for updating labels. Is that still correct, or is it something that should be done by Editor-in-Chief (EiC)? If it is the former, then I think a proper permission needs to be granted first. Adding this step to the aforementioned document can be helpful.

@lwasser 
Feel free to edit this comment.

**Comment by lwasser** [comment]
@NimaSarajpoor yes the editor should add labels. When an editor is onboarded, the EiC or someone on the pyos team should add them to the [editorial board team](https://github.com/orgs/pyOpenSci/teams/editorial-board) (and to our org). I suspect that step has not been happening. the documentation for this step [is here](https://www.pyopensci.org/software-peer-review/how-to/onboarding-guide.html#onboarding-a-new-editor). I wonder if we can somehow highlight it more? let me know what you think

**Comment by lwasser** [comment]
oh actually Nima you should have permissions. do you not have permissions to change labels? you are on the team!

**Comment by NimaSarajpoor** [comment]
@lwasser 
> do you not have permissions to change labels? you are on the team!

Apparently I do now! I did check it again after the second time! I can see the "gear" now next to the label section! Cool!

**Comment by lwasser** [comment]
hey @NimaSarajpoor do you think there is anything left on this issue to address? can we close? or do we need to update docs before we close? many thanks for opening this!

**Comment by willingc** [comment]
Closing as this seems resolved. Thanks!
