### ISSUE TITLE
Consider adding the guidebook to the top-level nav

### ISSUE THREAD

**Issue by choldgraf** [pyOpenSci/software-peer-review#54]
I think the guidebook is particularly useful for pyOpenSci authors/editors/reviewers. Currently it is 2 levels deep (on the "resources" page), but I wonder if it is useful enough to put as its own section at the top:

![image](https://user-images.githubusercontent.com/1839645/81124709-fc068a80-8eea-11ea-840a-55fb46fa8476.png)

Perhaps the "community forum" would be another item to put at the top, so that we know it is super discoverable...

**Comment by lwasser** [comment]
closing this now that we have 2 guidebooks and drop downs to show both!!
