### ISSUE TITLE
Split the authors guide into *requirements* and then guidelines/info

### ISSUE THREAD

**Issue by choldgraf** [pyOpenSci/software-peer-review#56]
Right now in the packaging guide, our "authors guide" has two kinds of information

* Basic guidelines for passing the review process
* More general information, best-practices, and examples

What do folks think about explicitly splitting these two things. Having one page that is just short and to-the-point "good/better/best" lists, and those lists then *link* to other pages in the guide that go into more detail

**Comment by lwasser** [comment]
hi @choldgraf !! we have totally reorganized this guide so i will go ahead and close this issue from may 2020!! how funny to look back on our early discussions around pyOpenSci!! :) hope you're well!!
