### ISSUE TITLE
add examples of pyOpenSci packages in process/aims_scope.html under each category

### ISSUE THREAD

**Issue by cosmicBboy** [pyOpenSci/software-peer-review#65]
It might be helpful for potential authors to see examples of pyOpenSci (or maybe ROpenSci?) that are representative of a particular package category, where possible.

**Comment by NickleDave** [comment]
Going through issues, noting this came up in https://github.com/pyOpenSci/python-package-guide/issues/21

**Comment by lwasser** [comment]
ah yes - this is being addressed - FINALLY here #162 !! funny this was open - i will close this as it's in progress but a great suggestion!!
