### ISSUE TITLE
How do we track packages that lose maintainers?

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/software-peer-review#76]
ropensci has documentation that specifies that they will fix things if the maintainer is not responsive. how does ropensci manage packages if they are not in our org and we don't have a good way ot tracking maintaince over time.

**Comment by choldgraf** [comment]
hmmm - the simplest way to do it is just to have good contact information and let users be the ones to say "hey XXX package isn't being maintained". Fancier solutions would be to implement a dashboard or something like this, but that may be too much burden

**Comment by lwasser** [comment]
thank you  @choldgraf but how would a user know to even tell us? the big difference here is that MOST packages in RO are actually in their organization so that connection is more clear (i think anyway). However in python we have such a community of developers that packages are all over the place and folks are i think much less likely to want to transfer over to us. does that make sense? i could be over thinking things too!

**Comment by choldgraf** [comment]
We could ask that people who have put their packages through the review process include a badge for pyOpenSci + some explanatory text in their README?

**Comment by lwasser** [comment]
Ok... so we are tracking this separately via our update-web-metadata package that will update stats associated with a package. we will be calculating some metrics that will help us flag packages that may be moving toward EOL / going unmaintained. closing this specific issue given that.
