### ISSUE TITLE
add link to COI on reviewers guide?

### ISSUE THREAD

**Issue by NickleDave** [pyOpenSci/software-peer-review#81]
Just borrowed the ROpenSci email template for inviting reviewers and noticed they point to the conflict of interest language in that email.

Should we have a link to the COI on the reviewers guide page?
I don't find one. Guess we need to fix #80 first

**Comment by lwasser** [comment]
hey @NickleDave  are you referring to this template:

https://www.pyopensci.org/contributing-guide/appendices/templates.html#review-request-template 

i think it would be great to link to it in the reviewers guide! maybe we can find a meeting time in the next month that folks can make and handle issues only?

**Comment by NickleDave** [comment]
Hi @lwasser sorry for not including more detail

I was referring to this page
https://www.pyopensci.org/contributing-guide/open-source-software-submissions/reviewer-guide.html
I thought it might make sense, since we have a link on the corresponding page for editors, under
https://www.pyopensci.org/contributing-guide/open-source-software-submissions/editors-guide.html#criteria-for-choosing-reviewers

JOSS for example has a link to the COI as the first thing on their reviewer's guide
https://joss.readthedocs.io/en/latest/review_checklist.html
I guess we could put it in the template too, since that's basically a cut-and-paste-able version of the checklist

and yes if we can plan a meeting in advance I'd be happy to join and work on these issues + the blog dev env instructions

**Comment by lwasser** [comment]
i'm looking at this but also i think that page needs an intro like what JOSS has. i'm happy to take a  stab at this a bit later!

in terms of the email template - @NickleDave  did you not  like the one here:

https://www.pyopensci.org/contributing-guide/appendices/templates.html#review-request-template 

we can make changes. One change i  can make it to make it "code" so it can be copied like the other templates. that is easy!

**Comment by lwasser** [comment]
i think we can close this @NickleDave if you think it's not been addressed please reopen!
